In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("s3programmer/disease-diagnosis-dataset")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/s3programmer/disease-diagnosis-dataset?dataset_version_number=1...

100%|██████████| 32.8k/32.8k [00:00<00:00, 38.7MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/s3programmer/disease-diagnosis-dataset/versions/1

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(path + "/disease_diagnosis.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Patient_ID           2000 non-null   int64
 1   Age                  2000 non-null   int64
 2   Gender               2000 non-null   object
 3   Symptom_1            2000 non-null   object
 4   Symptom_2            2000 non-null   object
 5   Symptom_3            2000 non-null   object
 6   Heart_Rate_bpm       2000 non-null   int64
 7   Body_Temperature_C   2000 non-null   float64
 8   Blood_Pressure_mmHg  2000 non-null   object
 9   Oxygen_Saturation_%  2000 non-null   int64
 10  Diagnosis            2000 non-null   object
 11  Severity             2000 non-null   object
 12  Treatment_Plan       2000 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 203.3+ KB

In [5]:
import pandas as pd
import numpy as np

# Combine all symptom columns into a single Series of lists
all_symptoms = df[['Symptom_1', 'Symptom_2', 'Symptom_3']].values.tolist()

# Flatten the list of lists and get unique symptoms
flat_list = [item for sublist in all_symptoms for item in sublist if pd.notna(item)]
unique_symptoms = list(set(flat_list))

# Create new columns for one-hot encoding
for symptom in unique_symptoms:
    df[symptom] = 0

# Populate the one-hot encoded columns
for index, row in df.iterrows():
    symptoms_in_row = [row['Symptom_1'], row['Symptom_2'], row['Symptom_3']]
    for symptom in symptoms_in_row:
        if pd.notna(symptom) and symptom in unique_symptoms:
            df.at[index, symptom] = 1

# Drop the original symptom columns if desired
# df = df.drop(['Symptom_1', 'Symptom_2', 'Symptom_3'], axis=1)

# Display the updated DataFrame with one-hot encoding
print(df.head())

   Patient_ID  Age  Gender            Symptom_1    Symptom_2 Symptom_3  \
0           1   74    Male              Fatigue  Sore throat     Fever
1           2   66  Female          Sore throat      Fatigue     Cough
2           3   32    Male            Body ache  Sore throat   Fatigue
3           4   21  Female  Shortness of breath     Headache     Cough
4           5   53    Male           Runny nose  Sore throat   Fatigue

   Heart_Rate_bpm  Body_Temperature_C Blood_Pressure_mmHg  \
0              69                39.4              132/91
1              95                39.0              174/98
2              77                36.8              136/60
3              72                38.9              147/82
4             100                36.6             109/106

   Oxygen_Saturation_%  ...  Severity       Treatment_Plan Runny nose  \
0                   94  ...  Moderate  Medication and rest          0
1                   98  ...      Mild      Rest and fluids          0
2                   96  ...      Mild      Rest and fluids          0
3                   99  ...      Mild      Rest and fluids          0
4                   92  ...      Mild      Rest and fluids          1

   Sore throat  Headache  Fever  Body ache  Fatigue  Shortness of breath  \
0            1         0      1          0        1                    0
1            1         0      0          0        1                    0
2            1         0      0          1        1                    0
3            0         1      0          0        0                    1
4            1         0      0          0        1                    0

   Cough
0      0
1      1
2      0
3      1
4      0

[5 rows x 21 columns]

In [6]:
import pandas as pd
# Perform one-hot encoding on the 'Diagnosis' column
diagnosis_one_hot = pd.get_dummies(df['Diagnosis'], prefix='Diagnosis')

# Convert the boolean values (True/False) to integers (1/0)
diagnosis_one_hot = diagnosis_one_hot.astype(int)

# Join the new one-hot encoded columns back to the original DataFrame
df = df.join(diagnosis_one_hot)

# Display the updated DataFrame
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Symptom_1', 'Symptom_2', 'Symptom_3',
       'Heart_Rate_bpm', 'Body_Temperature_C', 'Blood_Pressure_mmHg',
       'Oxygen_Saturation_%', 'Diagnosis', 'Severity', 'Treatment_Plan',
       'Runny nose', 'Sore throat', 'Headache', 'Fever', 'Body ache',
       'Fatigue', 'Shortness of breath', 'Cough', 'Diagnosis_Bronchitis',
       'Diagnosis_Cold', 'Diagnosis_Flu', 'Diagnosis_Healthy',
       'Diagnosis_Pneumonia'],
      dtype='object')

In [7]:
import pandas as pd
# Perform one-hot encoding on the 'Treatment_Plan' column
treatment_plan_one_hot = pd.get_dummies(df['Treatment_Plan'], prefix='Treatment_Plan')

# Convert the boolean values (True/False) to integers (1/0)
treatment_plan_one_hot = treatment_plan_one_hot.astype(int)

# Join the new one-hot encoded columns back to the original DataFrame
df = df.join(treatment_plan_one_hot)

# Display the updated DataFrame
print(df.head())
df.columns

   Patient_ID  Age  Gender            Symptom_1    Symptom_2 Symptom_3  \
0           1   74    Male              Fatigue  Sore throat     Fever
1           2   66  Female          Sore throat      Fatigue     Cough
2           3   32    Male            Body ache  Sore throat   Fatigue
3           4   21  Female  Shortness of breath     Headache     Cough
4           5   53    Male           Runny nose  Sore throat   Fatigue

   Heart_Rate_bpm  Body_Temperature_C Blood_Pressure_mmHg  \
0              69                39.4              132/91
1              95                39.0              174/98
2              77                36.8              136/60
3              72                38.9              147/82
4             100                36.6             109/106

   Oxygen_Saturation_%  ... Shortness of breath Cough Diagnosis_Bronchitis  \
0                   94  ...                   0     0                    0
1                   98  ...                   0     1                    0
2                   96  ...                   0     0                    0
3                   99  ...                   1     1                    0
4                   92  ...                   0     0                    0

   Diagnosis_Cold  Diagnosis_Flu  Diagnosis_Healthy  Diagnosis_Pneumonia  \
0               0              1                  0                    0
1               0              0                  1                    0
2               0              0                  1                    0
3               0              0                  1                    0
4               0              0                  1                    0

   Treatment_Plan_Hospitalization and medication  \
0                                              0
1                                              0
2                                              0
3                                              0
4                                              0

   Treatment_Plan_Medication and rest  Treatment_Plan_Rest and fluids
0                                   1                               0
1                                   0                               1
2                                   0                               1
3                                   0                               1
4                                   0                               1

[5 rows x 29 columns]

Index(['Patient_ID', 'Age', 'Gender', 'Symptom_1', 'Symptom_2', 'Symptom_3',
       'Heart_Rate_bpm', 'Body_Temperature_C', 'Blood_Pressure_mmHg',
       'Oxygen_Saturation_%', 'Diagnosis', 'Severity', 'Treatment_Plan',
       'Runny nose', 'Sore throat', 'Headache', 'Fever', 'Body ache',
       'Fatigue', 'Shortness of breath', 'Cough', 'Diagnosis_Bronchitis',
       'Diagnosis_Cold', 'Diagnosis_Flu', 'Diagnosis_Healthy',
       'Diagnosis_Pneumonia', 'Treatment_Plan_Hospitalization and medication',
       'Treatment_Plan_Medication and rest', 'Treatment_Plan_Rest and fluids'],
      dtype='object')

In [8]:
# prompt: want to do corr() so i need to pre process Blood_Pressure_mmHg column that has values such as '132/91' and '109/106' to columns systolic and average

import pandas as pd
# Function to extract systolic and calculate average blood pressure
def process_blood_pressure(bp_str):
    if isinstance(bp_str, str) and '/' in bp_str:
        try:
            systolic, diastolic = map(int, bp_str.split('/'))
            average = (systolic + diastolic) / 2
            return systolic, average
        except ValueError:
            return None, None  # Handle cases where conversion to int fails
    return None, None # Handle cases where format is not as expected

# Apply the function to create new columns
df[['Systolic_BP', 'Average_BP']] = df['Blood_Pressure_mmHg'].apply(lambda x: pd.Series(process_blood_pressure(x)))

# Display the updated DataFrame with new columns
print(df[['Blood_Pressure_mmHg', 'Systolic_BP', 'Average_BP']].head())

  Blood_Pressure_mmHg  Systolic_BP  Average_BP
0              132/91        132.0       111.5
1              174/98        174.0       136.0
2              136/60        136.0        98.0
3              147/82        147.0       114.5
4             109/106        109.0       107.5

In [9]:
# clean the df of irrelevant columns
binary_cols = df.drop(columns=['Patient_ID', 'Age', 'Gender', 'Symptom_1', 'Symptom_2', 'Symptom_3', 'Blood_Pressure_mmHg', 'Diagnosis', 'Treatment_Plan', 'Severity'])

# Create a new DataFrame with only these columns
case_base = binary_cols.copy()

print(case_base.head())
case_base.columns

   Heart_Rate_bpm  Body_Temperature_C  Oxygen_Saturation_%  Runny nose  \
0              69                39.4                   94           0
1              95                39.0                   98           0
2              77                36.8                   96           0
3              72                38.9                   99           0
4             100                36.6                   92           1

   Sore throat  Headache  Fever  Body ache  Fatigue  Shortness of breath  ...  \
0            1         0      1          0        1                    0  ...
1            1         0      0          0        1                    0  ...
2            1         0      0          1        1                    0  ...
3            0         1      0          0        0                    1  ...
4            1         0      0          0        1                    0  ...

   Diagnosis_Bronchitis  Diagnosis_Cold  Diagnosis_Flu  Diagnosis_Healthy  \
0                     0               0              1                  0
1                     0               0              0                  1
2                     0               0              0                  1
3                     0               0              0                  1
4                     0               0              0                  1

   Diagnosis_Pneumonia  Treatment_Plan_Hospitalization and medication  \
0                    0                                              0
1                    0                                              0
2                    0                                              0
3                    0                                              0
4                    0                                              0

   Treatment_Plan_Medication and rest  Treatment_Plan_Rest and fluids  \
0                                   1                               0
1                                   0                               1
2                                   0                               1
3                                   0                               1
4                                   0                               1

   Systolic_BP  Average_BP
0        132.0       111.5
1        174.0       136.0
2        136.0        98.0
3        147.0       114.5
4        109.0       107.5

[5 rows x 21 columns]

Index(['Heart_Rate_bpm', 'Body_Temperature_C', 'Oxygen_Saturation_%',
       'Runny nose', 'Sore throat', 'Headache', 'Fever', 'Body ache',
       'Fatigue', 'Shortness of breath', 'Cough', 'Diagnosis_Bronchitis',
       'Diagnosis_Cold', 'Diagnosis_Flu', 'Diagnosis_Healthy',
       'Diagnosis_Pneumonia', 'Treatment_Plan_Hospitalization and medication',
       'Treatment_Plan_Medication and rest', 'Treatment_Plan_Rest and fluids',
       'Systolic_BP', 'Average_BP'],
      dtype='object')

In [ ]:
case_base.to_csv('/content/case_base.csv')

In [ ]:
case_base.to_excel('/content/case_base.xlsx')

In [ ]:
case_base.head().to_excel('/content/case_base_head.xlsx')

In [ ]:
case_base.head(20).to_csv('/content/case_base_sampel.csv')

In [10]:
# Find columns that start with 'Treatment_Plan_'
Diagnosis_cols = [col for col in case_base.columns if col.startswith('Diagnosis_')]
# Select all columns except the Diagnosis columns
other_cols = [col for col in case_base.columns if col not in Diagnosis_cols]
# Calculate the correlation matrix between treatment plan columns and the rest
correlation_matrix = case_base[Diagnosis_cols].corrwith(case_base[other_cols])
print("Correlation between Treatment Plan columns and other columns:")
print(correlation_matrix)
# You can also calculate the full correlation matrix and then select the relevant part
full_correlation_matrix = case_base.corr()
# Select the correlation values between treatment plan columns and other columns
correlation_subset = full_correlation_matrix.loc[Diagnosis_cols, other_cols]
print("\nFull Correlation Matrix Subset (Treatment Plan vs Others):")
correlation_subset

Correlation between Treatment Plan columns and other columns:
Average_BP                                      NaN
Body ache                                       NaN
Body_Temperature_C                              NaN
Cough                                           NaN
Diagnosis_Bronchitis                            NaN
Diagnosis_Cold                                  NaN
Diagnosis_Flu                                   NaN
Diagnosis_Healthy                               NaN
Diagnosis_Pneumonia                             NaN
Fatigue                                         NaN
Fever                                           NaN
Headache                                        NaN
Heart_Rate_bpm                                  NaN
Oxygen_Saturation_%                             NaN
Runny nose                                      NaN
Shortness of breath                             NaN
Sore throat                                     NaN
Systolic_BP                                     NaN
Treatment_Plan_Hospitalization and medication   NaN
Treatment_Plan_Medication and rest              NaN
Treatment_Plan_Rest and fluids                  NaN
dtype: float64

Full Correlation Matrix Subset (Treatment Plan vs Others):

,Heart_Rate_bpm,Body_Temperature_C,Oxygen_Saturation_%,Runny nose,Sore throat,Headache,Fever,Body ache,Fatigue,Shortness of breath,Cough,Treatment_Plan_Hospitalization and medication,Treatment_Plan_Medication and rest,Treatment_Plan_Rest and fluids,Systolic_BP,Average_BP
Diagnosis_Bronchitis,-0.019529,-0.060803,-0.398186,-0.047697,-0.065831,-0.065716,-0.139802,-0.053469,-0.108520,-0.086402,0.564116,0.927503,-0.185133,-0.630847,0.008860,-0.001595
Diagnosis_Cold,0.003140,-0.398544,0.308225,-0.024927,0.012252,-0.005166,-0.003141,-0.011918,-0.040003,0.012761,0.060049,-0.143800,-0.123165,0.211422,-0.013453,-0.015731
Diagnosis_Flu,-0.090998,0.397418,0.064783,-0.071185,-0.061699,-0.037812,0.522031,-0.101969,-0.065344,-0.106228,-0.081009,-0.199603,1.000000,-0.582554,0.004328,-0.000561
Diagnosis_Healthy,0.025256,-0.064089,0.124812,0.110597,0.096424,0.080855,-0.322745,0.137417,0.156615,0.139881,-0.393755,-0.571391,-0.489396,0.840087,0.001302,0.012150
Diagnosis_Pneumonia,0.177978,0.156693,-0.137861,-0.032562,-0.031004,-0.003982,0.189361,-0.058181,-0.018503,-0.018503,-0.028043,0.310686,-0.062014,-0.211315,-0.012228,-0.006085

In [ ]:
correlation_subset.to_csv('/content/correlation_subset.csv')
print("Correlation subset saved to /content/correlation_subset.csv")

Correlation subset saved to /content/correlation_subset.csv

In [ ]:
correlation_subset.to_excel('/content/correlation_subset.xlsx')

In [ ]:
correlation_subset.head().to_csv('/content/correlation_subset_sampel.csv')

In [11]:
print("\nMemeriksa nilai kosong (NaN):")
print(df.isnull().sum())

print("\nMemeriksa nilai duplikat:")
print("Number of duplicate rows:", df.duplicated().sum())

Memeriksa nilai kosong (NaN):
Patient_ID                                       0
Age                                              0
Gender                                           0
Symptom_1                                        0
Symptom_2                                        0
Symptom_3                                        0
Heart_Rate_bpm                                   0
Body_Temperature_C                               0
Blood_Pressure_mmHg                              0
Oxygen_Saturation_%                              0
Diagnosis                                        0
Severity                                         0
Treatment_Plan                                   0
Runny nose                                       0
Sore throat                                      0
Headache                                         0
Fever                                            0
Body ache                                        0
Fatigue                                          0
Shortness of breath                              0
Cough                                            0
Diagnosis_Bronchitis                             0
Diagnosis_Cold                                   0
Diagnosis_Flu                                    0
Diagnosis_Healthy                                0
Diagnosis_Pneumonia                              0
Treatment_Plan_Hospitalization and medication    0
Treatment_Plan_Medication and rest               0
Treatment_Plan_Rest and fluids                   0
Systolic_BP                                      0
Average_BP                                       0
dtype: int64

Memeriksa nilai duplikat:
Number of duplicate rows: 0

In [12]:
features = ['Heart_Rate_bpm', 'Body_Temperature_C', 'Oxygen_Saturation_%',
       'Body ache', 'Headache', 'Shortness of breath', 'Cough', 'Fatigue',
       'Sore throat', 'Runny nose', 'Fever','Systolic_BP', 'Average_BP']

In [13]:
X = case_base[features].copy()
X.columns

Index(['Heart_Rate_bpm', 'Body_Temperature_C', 'Oxygen_Saturation_%',
       'Body ache', 'Headache', 'Shortness of breath', 'Cough', 'Fatigue',
       'Sore throat', 'Runny nose', 'Fever', 'Systolic_BP', 'Average_BP'],
      dtype='object')

In [14]:
symptoms = X.columns.tolist()
print(symptoms)

['Heart_Rate_bpm', 'Body_Temperature_C', 'Oxygen_Saturation_%', 'Body ache', 'Headache', 'Shortness of breath', 'Cough', 'Fatigue', 'Sore throat', 'Runny nose', 'Fever', 'Systolic_BP', 'Average_BP']

In [15]:
from sklearn.cluster import KMeans

# Handle potential NaN values by filling with 0 (or another suitable strategy)
X = X.fillna(0)

# Choose the number of clusters (you might need to experiment with this)
n_clusters = 5

# Initialize and fit the KMeans model
kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
case_base['Cluster'] = kmeans.fit_predict(X)

# Display the first few rows with the new 'Cluster' column
print(case_base[['Cluster'] + symptoms].head())

# You can also look at the distribution of data within each cluster
print("\nCluster sizes:")
print(case_base['Cluster'].value_counts())

# To understand the characteristics of each cluster, you can aggregate the mean values of the features within each cluster
print("\nCluster centers:")
print(case_base.groupby('Cluster')[symptoms].mean())

   Cluster  Heart_Rate_bpm  Body_Temperature_C  Oxygen_Saturation_%  \
0        1              69                39.4                   94
1        3              95                39.0                   98
2        1              77                36.8                   96
3        0              72                38.9                   99
4        4             100                36.6                   92

   Body ache  Headache  Shortness of breath  Cough  Fatigue  Sore throat  \
0          0         0                    0      0        1            1
1          0         0                    0      1        1            1
2          1         0                    0      0        1            1
3          0         1                    1      1        0            0
4          0         0                    0      0        1            1

   Runny nose  Fever  Systolic_BP  Average_BP
0           0      1        132.0       111.5
1           0      0        174.0       136.0
2           0      0        136.0        98.0
3           0      0        147.0       114.5
4           1      0        109.0       107.5

Cluster sizes:
Cluster
0    454
1    421
2    411
3    361
4    353
Name: count, dtype: int64

Cluster centers:
         Heart_Rate_bpm  Body_Temperature_C  Oxygen_Saturation_%  Body ache  \
Cluster
0             73.077093           37.763877            94.491189   0.365639
1             73.118765           37.764371            94.415677   0.380048
2            102.097324           37.810949            94.703163   0.369830
3            101.903047           37.709141            94.426593   0.346260
4            102.461756           37.634844            94.413598   0.382436

         Headache  Shortness of breath     Cough   Fatigue  Sore throat  \
Cluster
0        0.361233             0.381057  0.398678  0.378855     0.356828
1        0.342043             0.377672  0.396675  0.356295     0.370546
2        0.391727             0.374696  0.362530  0.384428     0.343066
3        0.415512             0.335180  0.407202  0.382271     0.337950
4        0.379603             0.422096  0.365439  0.390935     0.328612

         Runny nose     Fever  Systolic_BP  Average_BP
Cluster
0          0.374449  0.383260   157.024229  123.316079
1          0.375297  0.401425   113.273159  100.223278
2          0.396594  0.377129   135.481752  112.704380
3          0.382271  0.393352   166.836565  129.695291
4          0.359773  0.371105   103.611898   95.606232

In [16]:
print("number of columns:")
case_base.shape[1]

number of columns:

22

In [ ]:
# import pandas as pd
# # Calculate total number of entries
# total_entries = len(df)

# # Define the list of symptom columns to calculate rarity for

# # Create an empty list to store rarity data
# rarity_data = []

# # Calculate rarity for each symptom column
# for col in symptoms:
#     # Ensure the column exists and contains numerical data suitable for sum
#     if col in case_base.columns and pd.api.types.is_numeric_dtype(case_base[col]):
#         # Count the number of entries with value 1 in the column
#         count_ones = case_base[col].sum()
#         # Calculate rarity value
#         rarity_value = (total_entries - count_ones) * 10 / total_entries
#         # Append symptom and rounded rarity value to the list
#         rarity_data.append({'Symptom': col, 'Rarity Value': int(round(rarity_value))})
#     else:
#         print(f"Warning: Column '{col}' not found or not numerical. Skipping.")

# # Create a DataFrame from the rarity data
# rarity_df = pd.DataFrame(rarity_data)

# # Display the rarity table
# print("\nRarity Value of Symptoms:")
# rarity_df

Rarity Value of Symptoms:

                           Symptom  Rarity Value
0                      Sore throat             7
1                       Runny nose             6
2              Shortness of breath             6
3                        Body ache             6
4                            Fever             6
5                            Cough             6
6                         Headache             6
7                          Fatigue             6
8                  Heart_Rate_High             7
9    Body_Temperature_Fever (High)             6
10   Body_Temperature_Fever (Mild)             8
11             Blood_Pressure_High             5
12  Blood_Pressure_Prehypertension             6
13    Oxygen_Saturation_Mildly Low             5

#case_base -> dataframase kasus lama
#kmeans -> model clustering yang sudah training
#rarity_df -> pembobotan fitur

In [ ]:
# new_case = pd.DataFrame({
#     'Fatigue'                         : [0],
#     'Body ache'                       : [0],
#     'Headache'                        : [0],
#     'Runny nose'                      : [0],
#     'Sore throat'                     : [1],
#     'Headache'                        : [1],
#     'Fever'                           : [1],
#     'Shortness of breath'             : [0],
#     'Cough'                           : [0],
#     'Heart_Rate_High'                 : [0],
#     'Body_Temperature_Fever (High)'   : [1],
#     'Body_Temperature_Fever (Mild)'   : [0],
#     'Blood_Pressure_High'             : [0],
#     'Blood_Pressure_Prehypertension'  : [0],
#     'Oxygen_Saturation_Mildly Low'    : [0]
#   })

In [17]:
# prompt: new_case entry with the following attributes as according to case_base features. 'Heart_Rate_bpm', 'Body_Temperature_C', 'Oxygen_Saturation_%',
#        'Body ache', 'Headache', 'Shortness of breath', 'Cough', 'Fatigue',
#        'Sore throat', 'Runny nose', 'Fever','Systolic_BP', 'Average_BP'

import pandas as pd
new_case = pd.DataFrame({
    'Heart_Rate_bpm': [75],
    'Body_Temperature_C': [38.5],
    'Oxygen_Saturation_%': [95],
    'Body ache': [1],
    'Headache': [1],
    'Shortness of breath': [0],
    'Cough': [0],
    'Fatigue': [1],
    'Sore throat': [1],
    'Runny nose': [0],
    'Fever': [1],
    'Systolic_BP': [125],
    'Average_BP': [85]
})

#RETRIEVE

In [18]:
# prompt: predict cluster for new_case by closest centroid k-means model already fitted for case_base before

# Make sure the columns of the new case match the order of the training data (X)
new_case = new_case[X.columns]

# Predict the cluster for the new case
predicted_cluster = kmeans.predict(new_case)
new_case["Cluster"] = predicted_cluster

# Display the predicted cluster
print(f"The new case is predicted to belong to cluster: {predicted_cluster[0]}")

# You can now access the characteristics of the predicted cluster from the aggregated means
predicted_cluster_characteristics = case_base.groupby('Cluster')[symptoms].mean().loc[predicted_cluster[0]]
print(f"\nCharacteristics of the predicted cluster ({predicted_cluster[0]}):")
print(predicted_cluster_characteristics)

# You could also find the case(s) in the original case_base that belong to this cluster
# cases_ in_predicted_cluster = case_base[case_base['Cluster'] == predicted_cluster[0]]
# print(f"\nCases in the predicted cluster ({predicted_cluster[0]}):")
# print(cases_in_predicted_cluster.head())

The new case is predicted to belong to cluster: 1

Characteristics of the predicted cluster (1):
Heart_Rate_bpm          73.118765
Body_Temperature_C      37.764371
Oxygen_Saturation_%     94.415677
Body ache                0.380048
Headache                 0.342043
Shortness of breath      0.377672
Cough                    0.396675
Fatigue                  0.356295
Sore throat              0.370546
Runny nose               0.375297
Fever                    0.401425
Systolic_BP            113.273159
Average_BP             100.223278
Name: 1, dtype: float64

In [ ]:
# new_case_weights = {}
# for feature, value in new_case.iloc[0].items():
#     if value == 1:
#         rarity_value = rarity_df[rarity_df['Symptom'] == feature]['Rarity Value'].iloc[0].item()
#         new_case_weights[feature] = rarity_value
#     else:
#         new_case_weights[feature] = 0

# print("\Bobot fitur kasus baru:")
# new_case_weights

\Bobot fitur kasus baru:

{'Sore throat': 7,
 'Runny nose': 0,
 'Shortness of breath': 0,
 'Body ache': 0,
 'Fever': 6,
 'Cough': 0,
 'Headache': 6,
 'Fatigue': 0,
 'Heart_Rate_High': 0,
 'Body_Temperature_Fever (High)': 6,
 'Body_Temperature_Fever (Mild)': 0,
 'Blood_Pressure_High': 0,
 'Blood_Pressure_Prehypertension': 0,
 'Oxygen_Saturation_Mildly Low': 0,
 'Cluster': 0}

In [19]:
# prompt: compare the values of new_case and values of entries for case_base to find the case in case_base most similar to new_case. calculate with neighbor similarity

import pandas as pd
def weighted_neighbor_similarity(case1, case2, weights):
    """
    Calculates the weighted neighbor similarity between two cases.

    Args:
        case1 (pd.Series): The first case (as a pandas Series).
        case2 (pd.Series): The second case (as a pandas Series).
        weights (dict): A dictionary where keys are feature names and values
                        are their weights.

    Returns:
        float: The weighted neighbor similarity score.
    """
    intersection = 0
    union = 0
    for feature in weights:
        weight = weights[feature]
        if case1[feature] == 1 and case2[feature] == 1:
            intersection += weight
        if case1[feature] == 1 or case2[feature] == 1:
            union += weight

    # Avoid division by zero if union is 0
    if union == 0:
        return 0
    return intersection / union

# Calculate weights based on rarity (or any other desired method)
# For simplicity, let's use a basic weight based on the feature's presence
# in the training data. You can replace this with your rarity calculation.
feature_weights = {}
for col in features:
  # Simple weight: 1 if present in at least one training case, 0 otherwise
  feature_weights[col] = 1 if case_base[col].sum() > 0 else 0

# Ensure weights are calculated for all relevant features
# You might want to use your rarity_df for a more sophisticated weighting
# For demonstration, let's use a simple equal weight for all features in `features`
feature_weights = {feature: 1 for feature in features}


# Initialize variables to store the best similarity and the most similar case
best_similarity = -1
most_similar_case_index = -1

# Iterate through each case in the case_base
for index, case_entry in case_base[features].iterrows():
    # Calculate the weighted neighbor similarity between the new case and the current case entry
    similarity = weighted_neighbor_similarity(new_case.iloc[0][features], case_entry, feature_weights)

    # Update the best similarity and the index of the most similar case if the current similarity is better
    if similarity > best_similarity:
        best_similarity = similarity
        most_similar_case_index = index

# Get the most similar case entry from the original DataFrame (or case_base)
most_similar_case = case_base.iloc[most_similar_case_index]

print(f"\nMost similar case found at index: {most_similar_case_index}")
print(f"Weighted Neighbor Similarity: {best_similarity:.4f}")
print("\nDetails of the most similar case:")
print(most_similar_case)

# You can also retrieve the original row from the 'df' DataFrame
# using the index if you need more columns than what's in case_base
original_most_similar_row = df.iloc[most_similar_case_index]
print("\nOriginal details from the full dataset:")
original_most_similar_row

Most similar case found at index: 0
Weighted Neighbor Similarity: 0.6000

Details of the most similar case:
Heart_Rate_bpm                                    69.0
Body_Temperature_C                                39.4
Oxygen_Saturation_%                               94.0
Runny nose                                         0.0
Sore throat                                        1.0
Headache                                           0.0
Fever                                              1.0
Body ache                                          0.0
Fatigue                                            1.0
Shortness of breath                                0.0
Cough                                              0.0
Diagnosis_Bronchitis                               0.0
Diagnosis_Cold                                     0.0
Diagnosis_Flu                                      1.0
Diagnosis_Healthy                                  0.0
Diagnosis_Pneumonia                                0.0
Treatment_Plan_Hospitalization and medication      0.0
Treatment_Plan_Medication and rest                 1.0
Treatment_Plan_Rest and fluids                     0.0
Systolic_BP                                      132.0
Average_BP                                       111.5
Cluster                                            1.0
Name: 0, dtype: float64

Original details from the full dataset:

Patient_ID                                                         1
Age                                                               74
Gender                                                          Male
Symptom_1                                                    Fatigue
Symptom_2                                                Sore throat
Symptom_3                                                      Fever
Heart_Rate_bpm                                                    69
Body_Temperature_C                                              39.4
Blood_Pressure_mmHg                                           132/91
Oxygen_Saturation_%                                               94
Diagnosis                                                        Flu
Severity                                                    Moderate
Treatment_Plan                                   Medication and rest
Runny nose                                                         0
Sore throat                                                        1
Headache                                                           0
Fever                                                              1
Body ache                                                          0
Fatigue                                                            1
Shortness of breath                                                0
Cough                                                              0
Diagnosis_Bronchitis                                               0
Diagnosis_Cold                                                     0
Diagnosis_Flu                                                      1
Diagnosis_Healthy                                                  0
Diagnosis_Pneumonia                                                0
Treatment_Plan_Hospitalization and medication                      0
Treatment_Plan_Medication and rest                                 1
Treatment_Plan_Rest and fluids                                     0
Systolic_BP                                                    132.0
Average_BP                                                     111.5
Name: 0, dtype: object

In [ ]:
# prompt: find most similar case in case_base (same cluster) to new_case with neighbor similarity by observing the VALUES of the columns

import numpy as np
from scipy.spatial.distance import euclidean

# Filter case_base to include only cases in the predicted cluster
cases_in_predicted_cluster = case_base[case_base['Cluster'] == predicted_cluster[0]].copy()

# Define a function to calculate similarity using inverse euclidean distance weighted by rarity
def weighted_inverse_euclidean_similarity(case1, case2, weights):
    """Calculates weighted inverse Euclidean similarity between two cases."""
    # Ensure both cases have the same columns and order as weights
    case1_aligned = case1[weights.keys()]
    case2_aligned = case2[weights.keys()]

    # Calculate weighted squared differences
    weighted_sq_diff = sum((weights[col] * (case1_aligned[col] - case2_aligned[col]))**2 for col in weights.keys())

    # Calculate weighted Euclidean distance
    weighted_dist = np.sqrt(weighted_sq_diff)

    # Calculate inverse Euclidean distance (add a small constant to avoid division by zero)
    similarity = 1 / (1 + weighted_dist)
    return similarity

# Calculate similarity of the new case with all cases in the predicted cluster
similarities = cases_in_predicted_cluster.apply(
    lambda row: weighted_inverse_euclidean_similarity(new_case.iloc[0], row, new_case_weights),
    axis=1
)

# Find the index of the case with the highest similarity
most_similar_case_index = similarities.idxmax()

# Retrieve the most similar case from the original case_base using the index
most_similar_case = case_base.loc[most_similar_case_index]

print("\nMost similar case in the same cluster:")
print(most_similar_case)

print(f"\nSimilarity score with the most similar case: {similarities.max()}")

# You can now access the original data for the most similar case from the full df
original_most_similar_data = df.loc[most_similar_case_index]
print("\nOriginal data for the most similar case:")
print(original_most_similar_data[['Diagnosis', 'Treatment_Plan', 'Severity']])

NameError: name 'new_case_weights' is not defined

In [ ]:
def calculate_weighted_similarity(case1, case2, weights):
    similarity = 0
    total_weight = sum(new_case.values())
    # total_weight = sum(weights.values())
    if total_weight == 0:  # Avoid division by zero if all weights are zero
        return 0

    for feature in case1.keys():
        # Ensure features exist in both cases
        if feature in case1 and feature in case2:
            # Simple matching for binary features (0 or 1)
            if case1[feature] == case2[feature]:
                similarity += weights[feature]
    return similarity / total_weight

# Filter old cases that belong to the predicted cluster
old_cases_in_predicted_cluster = case_base[case_base['Cluster'] == predicted_cluster[0]].copy()

# Calculate weighted similarity for each old case in the predicted cluster
similarities = []
for index, row in old_cases_in_predicted_cluster.iterrows():
    similarity = calculate_weighted_similarity(new_case.iloc[0], row, new_case_weights)
    similarities.append((index, similarity))

# Find the case with the highest similarity
most_similar_case_index, max_similarity = max(similarities, key=lambda item: item[1])

# Get the most similar case from the original case_base
most_similar_case = case_base.loc[most_similar_case_index]

print(f"\nMost similar case to the new case (within predicted cluster {predicted_cluster[0]}):")
print(f"Index in case_base: {most_similar_case_index}")
print(f"Weighted Similarity: {max_similarity:.4f}")
print("\nDetails of the most similar case:")
most_similar_case

Most similar case to the new case (within predicted cluster 0):
Index in case_base: 26
Weighted Similarity: 1.0000

Details of the most similar case:

Sore throat                                      1
Runny nose                                       0
Shortness of breath                              0
Body ache                                        0
Fever                                            1
Cough                                            0
Headache                                         1
Fatigue                                          0
Heart_Rate_High                                  0
Body_Temperature_Fever (High)                    1
Body_Temperature_Fever (Mild)                    0
Blood_Pressure_High                              1
Blood_Pressure_Prehypertension                   0
Oxygen_Saturation_Mildly Low                     0
Diagnosis_Bronchitis                             0
Diagnosis_Cold                                   0
Diagnosis_Flu                                    1
Diagnosis_Healthy                                0
Diagnosis_Pneumonia                              0
Treatment_Plan_Hospitalization and medication    0
Treatment_Plan_Medication and rest               1
Treatment_Plan_Rest and fluids                   0
Cluster                                          0
Name: 26, dtype: int64

### most_similar_case -> barisan kasus lama paling mirip
### most_similar_case_index -> index kasus lama paling mirip

#REUSE

In [20]:
diagnosis_cols = [col for col in most_similar_case.index if col.startswith('Diagnosis_')]
treatment_plan_cols = [col for col in most_similar_case.index if col.startswith('Treatment_Plan_')]

for col in diagnosis_cols:
  new_case[col] = most_similar_case[col]

for col in treatment_plan_cols:
  new_case[col] = most_similar_case[col]

print(new_case)

   Heart_Rate_bpm  Body_Temperature_C  Oxygen_Saturation_%  Body ache  \
0              75                38.5                   95          1

   Headache  Shortness of breath  Cough  Fatigue  Sore throat  Runny nose  \
0         1                    0      0        1            1           0

   ...  Average_BP  Cluster  Diagnosis_Bronchitis  Diagnosis_Cold  \
0  ...          85        1                   0.0             0.0

   Diagnosis_Flu  Diagnosis_Healthy  Diagnosis_Pneumonia  \
0            1.0                0.0                  0.0

   Treatment_Plan_Hospitalization and medication  \
0                                            0.0

   Treatment_Plan_Medication and rest  Treatment_Plan_Rest and fluids
0                                 1.0                             0.0

[1 rows x 22 columns]

# REVISE

In [ ]:
print(symptoms)

['Sore throat', 'Runny nose', 'Shortness of breath', 'Body ache', 'Fever', 'Cough', 'Headache', 'Fatigue', 'Heart_Rate_High', 'Body_Temperature_Fever (High)', 'Body_Temperature_Fever (Mild)', 'Blood_Pressure_High', 'Blood_Pressure_Prehypertension', 'Oxygen_Saturation_Mildly Low']

In [21]:
from sklearn.naive_bayes import GaussianNB

X_nb = case_base[symptoms]

treatment_plan_models = {} #menampung model untuk setiap jenis perawatan

for treatment_col in treatment_plan_cols:
  y_nb = case_base[treatment_col]

  nb_model = GaussianNB()
  nb_model.fit(X_nb, y_nb)
  treatment_plan_models[treatment_col] = nb_model

new_case_symptoms = new_case[symptoms]

treatment_plan_probabilities = {}#menampung nilai kepercayaan prediksi model setiap jenis perawatan
for treatment_col, model in treatment_plan_models.items():
  treatment_plan_probabilities[treatment_col] = model.predict_proba(new_case_symptoms)[:, 1][0]

print("\nNilai kepercayaan Naive Bayes kasus baru untuk setiap jenis perawatan :")
print(treatment_plan_probabilities)

best_treatment_plan_col = max(treatment_plan_probabilities, key=treatment_plan_probabilities.get)
highest_probability = treatment_plan_probabilities[best_treatment_plan_col]

print(f"\nBest Treatment Plan based on Naive Bayes probability: {best_treatment_plan_col}")
print(f"Highest Probability: {highest_probability:.4f}")

if best_treatment_plan_col in new_case.columns:
    new_case[best_treatment_plan_col] = 1 # Set the recommended treatment plan to 1
else:
    print(f"Warning: Recommended treatment plan '{best_treatment_plan_col}' not found in new_case columns.")


print("\nNew case DataFrame after Naive Bayes recommendation:")
new_case[treatment_plan_cols]

Nilai kepercayaan Naive Bayes kasus baru untuk setiap jenis perawatan :
{'Treatment_Plan_Hospitalization and medication': np.float64(6.388899472447188e-05), 'Treatment_Plan_Medication and rest': np.float64(0.9975829295581097), 'Treatment_Plan_Rest and fluids': np.float64(0.8180208345826964)}

Best Treatment Plan based on Naive Bayes probability: Treatment_Plan_Medication and rest
Highest Probability: 0.9976

New case DataFrame after Naive Bayes recommendation:

,Treatment_Plan_Hospitalization and medication,Treatment_Plan_Medication and rest,Treatment_Plan_Rest and fluids
0,0.0,1,0.0

In [ ]:
case_base = pd.concat([case_base, new_case], ignore_index=True)
print("\nKasus baru di indeks terakhir case_base:")
print(case_base.tail())

Kasus baru di indeks terakhir case_base:
      Sore throat  Runny nose  Shortness of breath  Body ache  Fever  Cough  \
1996            1           0                    0          0      0      1
1997            0           1                    0          0      1      0
1998            1           0                    0          0      0      1
1999            0           0                    0          1      1      0
2000            1           0                    0          0      1      0

      Headache  Fatigue  Heart_Rate_High  Body_Temperature_Fever (High)  ...  \
1996         0        1                0                              0  ...
1997         0        1                0                              0  ...
1998         1        0                0                              1  ...
1999         0        1                1                              0  ...
2000         1        0                0                              1  ...

      Oxygen_Saturation_Mildly Low  Diagnosis_Bronchitis  Diagnosis_Cold  \
1996                             0                     0               1
1997                             0                     0               0
1998                             1                     1               0
1999                             1                     0               0
2000                             0                     0               0

      Diagnosis_Flu  Diagnosis_Healthy  Diagnosis_Pneumonia  \
1996              0                  0                    0
1997              0                  1                    0
1998              0                  0                    0
1999              0                  1                    0
2000              1                  0                    0

      Treatment_Plan_Hospitalization and medication  \
1996                                              0
1997                                              0
1998                                              1
1999                                              0
2000                                              0

      Treatment_Plan_Medication and rest  Treatment_Plan_Rest and fluids  \
1996                                   0                               1
1997                                   0                               1
1998                                   0                               0
1999                                   0                               1
2000                                   1                               0

      Cluster
1996        4
1997        0
1998        1
1999        2
2000        0

[5 rows x 23 columns]

In [22]:
print(features)

['Heart_Rate_bpm', 'Body_Temperature_C', 'Oxygen_Saturation_%', 'Body ache', 'Headache', 'Shortness of breath', 'Cough', 'Fatigue', 'Sore throat', 'Runny nose', 'Fever', 'Systolic_BP', 'Average_BP']